name: Execute test with Selenium Grid

on: [push]

jobs:
  execute-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Selenium Grid
        run: docker compose up -d --scale chrome=3 --scale firefox=3
      - name: check docker status
        run: docker ps
       
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Executing test
        run: mvn clean test -DgridUrl=http://localhost:4444 -Dbrowser=CHROME -Dheadless=true

      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Automation Allure-report
          path: target/allure-results
          retention-days: 7

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: target/allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy report to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history

      - name: Tear down Grid
        if: always()
        run: docker compose down