name: Execute test with Selenium Grid

on: [push]

jobs:
  execute-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Selenium Grid
        run: docker-compose up -d --scale chrome=3 --scale firefox=3
      - name: check docker status
        run: docker ps
       
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Executing test
        run: mvn clean test -DgridUrl=http://localhost:4444 -Dbrowser=CHROME -Dheadless=true

      - name: Tear down Grid
        if: always()
        run: docker-compose down